# Generated by Django 4.2.4 on 2023-08-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('name', models.CharField(max_length=70)),
                ('dept', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('pas', models.CharField(max_length=70)),
            ],
        ),
    ]
