# Generated by Django 4.2.4 on 2023-08-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stutdent',
            name='stu_email',
            field=models.EmailField(default='Not available', max_length=70),
        ),
    ]
